/*****************************************************************************************
* Harmonizer 01 - A rule-based harmonizer for SuperCollider								 *
* Copyright (C) 2025 Siriil																 *
* Licensed under GPLv3. See LICENSE file for details.									 *
*****************************************************************************************/
(
"./utils.scd".loadRelative;
"./message.scd".loadRelative;
"./fixtures.scd".loadRelative;
"../test_range.scd".loadRelative;
"../test_backtrack.scd".loadRelative;
"../test_chordrules.scd".loadRelative;
"../test_validators.scd".loadRelative;
)