/**************************************************************************************
- HARMONY 01 / Load all test files
**************************************************************************************/
(
"./utils.scd".loadRelative;
"./message.scd".loadRelative;
"./fixtures.scd".loadRelative;
"../test_range.scd".loadRelative;
"../test_backtrack.scd".loadRelative;
"../test_chordrules.scd".loadRelative;
"../test_validators.scd".loadRelative;
)