/**************************************************************************************
- HARMONY 01 / Load all test files
**************************************************************************************/
(
"./utils.scd".loadRelative;
"./fixtures.scd".loadRelative;
"./messages.scd".loadRelative;
"../test_backtrack.scd".loadRelative;
"../test_chordrules.scd".loadRelative;
"../test_range.scd".loadRealative;
)